/*
	Admin Permissions
*/

#define ADMIN_RIGHTS_ADMIN		"ADMIN"
#define ADMIN_RIGHTS_DEBUG		"DEBUG"
#define ADMIN_RIGHTS_SUPER		"SUPER"

#define ADMIN_RIGHTS_ALL_RIGHTS	list(ADMIN_RIGHTS_ADMIN, ADMIN_RIGHTS_DEBUG, ADMIN_RIGHTS_SUPER)
#define ADMIN_RIGHTS_HOST		ADMIN_RIGHTS_ALL_RIGHTS




